import React from 'react';
import Head from "next/head";
import TopNav from '../navbar/topNavbar';
import MainNavbar from '../navbar/mainNavbar';

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>HighTable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
      <MainNavbar />
      {children}
    </div>
  );
}

export default Layout;
